name: Auto Assign PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  assign-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from dev to test or test to master
        id: check-branches
        run: |
          BASE_BRANCH="${{ github.base_ref }}"
          HEAD_BRANCH="${{ github.head_ref }}"
          
          if [[ "$BASE_BRANCH" == "test" && "$HEAD_BRANCH" == "dev" ]] || [[ "$BASE_BRANCH" == "main" && "$HEAD_BRANCH" == "test" ]]; then
            echo "::set-output name=should_assign::true"
          else
            echo "::set-output name=should_assign::false"
          fi

      - name: Assign PR to admin
        if: steps.check-branches.outputs.should_assign == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: assignee } = await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['your-github-username'],
            });
            console.log(`Assigned PR to: ${assignee.assignees.map(a => a.login).join(', ')}`);