name: Flake8 Linting on dev push

on:
  push:
    branches:
      - dev
  # pull_request:
  #   branches:
  #     - dev
  #     - main
  #     - test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Run Flake8
      run: |
        # Fail the workflow if there are any linting errors
        flake8 . --count --max-line-length=127 --statistics
      continue-on-error: false