name: Flake8 Linting

on:
  push:
    branches: 
      - dev
      - main
      - test
  pull_request:
    branches: 
      - dev
      - main
      - test

jobs:
  flake8-lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      
      - name: Run Flake8
        id: flake8-lint
        run: |
          # Use exit-zero to set a non-zero exit code if linting fails
          flake8 . --exit-zero --count --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: false