name: Restrict Merge to Admin Only

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - test
      - main


permissions:
  pull-requests: write
  issues: write

jobs:
  check-pr-author:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR author
        id: check-author
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          ADMIN_USER="your-github-username" # Replace with your GitHub username

          if [[ "$PR_AUTHOR" == "$ADMIN_USER" ]]; then
            echo "allow_merge=true" >> $GITHUB_OUTPUT
          else
            echo "allow_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Block merge for collaborators
        if: steps.check-author.outputs.allow_merge == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const ADMIN_USER = "your-github-username"; // Replace with your GitHub username

            if (pr.user.login !== ADMIN_USER) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: '🚫 Only the admin can merge this pull request. Please wait for the admin to review and merge.',
              });

              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                state: 'closed', // Close the PR to block merging
              });
            }