name: Flake8 Linting

on:
  pull_request:
    branches: [ test, main ]
    
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'  # Set to the version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 .
        
  test:
    runs-on: ubuntu-latest

    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.0'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --force-reinstall numpy
          pip install scikit-learn==1.3.2  # Ensure correct version
          pip install -r requirements.txt

      - name: Verify Installed Versions
        run: |
          python -c "import sklearn; print('scikit-learn:', sklearn.__version__)"
          python -c "import numpy; print('numpy:', numpy.__version__)"

      - name: Run Unit Tests
        run: python -m unittest test_model.py
