name: Feature Testing

on:
  pull_request:
    branches: [ test ]  # Triggers when merging into 'test'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13.2'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --force-reinstall numpy
          pip install scikit-learn==1.3.2  # Ensure correct version
          pip install -r requirements.txt

      - name: Verify Installed Versions
        run: |
          python -c "import sklearn; print('scikit-learn:', sklearn.__version__)"
          python -c "import numpy; print('numpy:', numpy.__version__)"

      - name: Run Unit Tests
        run: python -m unittest test_model.py
